name: BetturPlugin
version: '1.0'
main: ethebee3.BetturPlugin.Main
api-version: '1.20'

commands:
  spawn:
    description: Teleport to the spawn location.
    usage: /spawn
  setspawn:
    description: Set the spawn location to your current position.
    usage: /setspawn
  staffchat:
    discription: staff chat
    usage: /staffchat
    aliases: [sc]
  clearchat:
    discription: clear chat
    usage: /cc
    aliases: [cc]
  pvp:
    discription: toggle pvp
    usage: /pvp [on/off]
#  dupe:
#    description: Dupe Your Items
#    usage: /<command>
